category:
  kinds:
    - Arts
    - Biographies
    - Business
    - Children's
    - Comics
    - Computers
    - Cooking
    - Crafts
    - Engineering
    - Entertainment
    - Health
    - History
    - Humour
    - Law
    - Literature
    - Mathematics
    - Medicine
    - News
    - Others
    - Reference
    - Relationships
    - Religion
    - Politics
    - Science
    - Self-Help
    - Sports
    - Travel

asset:
  kinds:
    - Book
    - Periodical
    - Magazine
    - Newspaper
    - Compact Disc
    - DVD
  formats:
    - Paperback
    - Hardbound
    - Cased
  languages:
    - Malayalam
    - English
    - Hindi
    - Tamil
    - Kannada
    - Arabic
    - Other
  ratings:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10

format:
  date: 'yyyy-mm-dd'